# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_1_1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 480)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frameWeather = QtWidgets.QFrame(self.centralwidget)
        self.frameWeather.setGeometry(QtCore.QRect(0, 230, 800, 230))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.frameWeather.setFont(font)
        self.frameWeather.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameWeather.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameWeather.setObjectName("frameWeather")
        self.uhrzeit1 = QtWidgets.QLabel(self.frameWeather)
        self.uhrzeit1.setGeometry(QtCore.QRect(25, 10, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.uhrzeit1.setFont(font)
        self.uhrzeit1.setAlignment(QtCore.Qt.AlignCenter)
        self.uhrzeit1.setObjectName("uhrzeit1")
        self.image1 = QtWidgets.QLabel(self.frameWeather)
        self.image1.setGeometry(QtCore.QRect(25, 40, 80, 80))
        self.image1.setText("")
        self.image1.setPixmap(QtGui.QPixmap("icons/01d.png"))
        self.image1.setScaledContents(True)
        self.image1.setObjectName("image1")
        self.temperatur1 = QtWidgets.QLabel(self.frameWeather)
        self.temperatur1.setGeometry(QtCore.QRect(25, 120, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.temperatur1.setFont(font)
        self.temperatur1.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatur1.setObjectName("temperatur1")
        self.wind1 = QtWidgets.QLabel(self.frameWeather)
        self.wind1.setGeometry(QtCore.QRect(25, 150, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.wind1.setFont(font)
        self.wind1.setAlignment(QtCore.Qt.AlignCenter)
        self.wind1.setObjectName("wind1")
        self.regen1 = QtWidgets.QLabel(self.frameWeather)
        self.regen1.setGeometry(QtCore.QRect(25, 180, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.regen1.setFont(font)
        self.regen1.setAlignment(QtCore.Qt.AlignCenter)
        self.regen1.setObjectName("regen1")
        self.regen2 = QtWidgets.QLabel(self.frameWeather)
        self.regen2.setGeometry(QtCore.QRect(155, 180, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.regen2.setFont(font)
        self.regen2.setAlignment(QtCore.Qt.AlignCenter)
        self.regen2.setObjectName("regen2")
        self.uhrzeit2 = QtWidgets.QLabel(self.frameWeather)
        self.uhrzeit2.setGeometry(QtCore.QRect(155, 10, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.uhrzeit2.setFont(font)
        self.uhrzeit2.setAlignment(QtCore.Qt.AlignCenter)
        self.uhrzeit2.setObjectName("uhrzeit2")
        self.temperatur2 = QtWidgets.QLabel(self.frameWeather)
        self.temperatur2.setGeometry(QtCore.QRect(155, 120, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.temperatur2.setFont(font)
        self.temperatur2.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatur2.setObjectName("temperatur2")
        self.wind2 = QtWidgets.QLabel(self.frameWeather)
        self.wind2.setGeometry(QtCore.QRect(155, 150, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.wind2.setFont(font)
        self.wind2.setAlignment(QtCore.Qt.AlignCenter)
        self.wind2.setObjectName("wind2")
        self.image2 = QtWidgets.QLabel(self.frameWeather)
        self.image2.setGeometry(QtCore.QRect(155, 40, 80, 80))
        self.image2.setText("")
        self.image2.setPixmap(QtGui.QPixmap("icons/02d.png"))
        self.image2.setScaledContents(True)
        self.image2.setObjectName("image2")
        self.regen3 = QtWidgets.QLabel(self.frameWeather)
        self.regen3.setGeometry(QtCore.QRect(285, 180, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.regen3.setFont(font)
        self.regen3.setAlignment(QtCore.Qt.AlignCenter)
        self.regen3.setObjectName("regen3")
        self.uhrzeit3 = QtWidgets.QLabel(self.frameWeather)
        self.uhrzeit3.setGeometry(QtCore.QRect(285, 10, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.uhrzeit3.setFont(font)
        self.uhrzeit3.setAlignment(QtCore.Qt.AlignCenter)
        self.uhrzeit3.setObjectName("uhrzeit3")
        self.temperatur3 = QtWidgets.QLabel(self.frameWeather)
        self.temperatur3.setGeometry(QtCore.QRect(285, 120, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.temperatur3.setFont(font)
        self.temperatur3.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatur3.setObjectName("temperatur3")
        self.wind3 = QtWidgets.QLabel(self.frameWeather)
        self.wind3.setGeometry(QtCore.QRect(285, 150, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.wind3.setFont(font)
        self.wind3.setAlignment(QtCore.Qt.AlignCenter)
        self.wind3.setObjectName("wind3")
        self.image3 = QtWidgets.QLabel(self.frameWeather)
        self.image3.setGeometry(QtCore.QRect(285, 40, 80, 80))
        self.image3.setText("")
        self.image3.setPixmap(QtGui.QPixmap("icons/03d.png"))
        self.image3.setScaledContents(True)
        self.image3.setObjectName("image3")
        self.regen4 = QtWidgets.QLabel(self.frameWeather)
        self.regen4.setGeometry(QtCore.QRect(415, 180, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.regen4.setFont(font)
        self.regen4.setAlignment(QtCore.Qt.AlignCenter)
        self.regen4.setObjectName("regen4")
        self.uhrzeit4 = QtWidgets.QLabel(self.frameWeather)
        self.uhrzeit4.setGeometry(QtCore.QRect(415, 10, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.uhrzeit4.setFont(font)
        self.uhrzeit4.setAlignment(QtCore.Qt.AlignCenter)
        self.uhrzeit4.setObjectName("uhrzeit4")
        self.temperatur4 = QtWidgets.QLabel(self.frameWeather)
        self.temperatur4.setGeometry(QtCore.QRect(415, 120, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.temperatur4.setFont(font)
        self.temperatur4.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatur4.setObjectName("temperatur4")
        self.wind4 = QtWidgets.QLabel(self.frameWeather)
        self.wind4.setGeometry(QtCore.QRect(415, 150, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.wind4.setFont(font)
        self.wind4.setAlignment(QtCore.Qt.AlignCenter)
        self.wind4.setObjectName("wind4")
        self.image4 = QtWidgets.QLabel(self.frameWeather)
        self.image4.setGeometry(QtCore.QRect(415, 40, 80, 80))
        self.image4.setText("")
        self.image4.setPixmap(QtGui.QPixmap("icons/04d.png"))
        self.image4.setScaledContents(True)
        self.image4.setObjectName("image4")
        self.regen5 = QtWidgets.QLabel(self.frameWeather)
        self.regen5.setGeometry(QtCore.QRect(545, 180, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.regen5.setFont(font)
        self.regen5.setAlignment(QtCore.Qt.AlignCenter)
        self.regen5.setObjectName("regen5")
        self.uhrzeit5 = QtWidgets.QLabel(self.frameWeather)
        self.uhrzeit5.setGeometry(QtCore.QRect(545, 10, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.uhrzeit5.setFont(font)
        self.uhrzeit5.setAlignment(QtCore.Qt.AlignCenter)
        self.uhrzeit5.setObjectName("uhrzeit5")
        self.temperatur5 = QtWidgets.QLabel(self.frameWeather)
        self.temperatur5.setGeometry(QtCore.QRect(545, 120, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.temperatur5.setFont(font)
        self.temperatur5.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatur5.setObjectName("temperatur5")
        self.wind5 = QtWidgets.QLabel(self.frameWeather)
        self.wind5.setGeometry(QtCore.QRect(545, 150, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.wind5.setFont(font)
        self.wind5.setAlignment(QtCore.Qt.AlignCenter)
        self.wind5.setObjectName("wind5")
        self.image5 = QtWidgets.QLabel(self.frameWeather)
        self.image5.setGeometry(QtCore.QRect(545, 40, 80, 80))
        self.image5.setText("")
        self.image5.setPixmap(QtGui.QPixmap("icons/09d.png"))
        self.image5.setScaledContents(True)
        self.image5.setObjectName("image5")
        self.regen6 = QtWidgets.QLabel(self.frameWeather)
        self.regen6.setGeometry(QtCore.QRect(675, 180, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.regen6.setFont(font)
        self.regen6.setAlignment(QtCore.Qt.AlignCenter)
        self.regen6.setObjectName("regen6")
        self.uhrzeit6 = QtWidgets.QLabel(self.frameWeather)
        self.uhrzeit6.setGeometry(QtCore.QRect(675, 10, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.uhrzeit6.setFont(font)
        self.uhrzeit6.setAlignment(QtCore.Qt.AlignCenter)
        self.uhrzeit6.setObjectName("uhrzeit6")
        self.temperatur6 = QtWidgets.QLabel(self.frameWeather)
        self.temperatur6.setGeometry(QtCore.QRect(675, 120, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.temperatur6.setFont(font)
        self.temperatur6.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatur6.setObjectName("temperatur6")
        self.wind6 = QtWidgets.QLabel(self.frameWeather)
        self.wind6.setGeometry(QtCore.QRect(675, 150, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.wind6.setFont(font)
        self.wind6.setAlignment(QtCore.Qt.AlignCenter)
        self.wind6.setObjectName("wind6")
        self.image6 = QtWidgets.QLabel(self.frameWeather)
        self.image6.setGeometry(QtCore.QRect(675, 40, 80, 80))
        self.image6.setText("")
        self.image6.setPixmap(QtGui.QPixmap("icons/10d.png"))
        self.image6.setScaledContents(True)
        self.image6.setObjectName("image6")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 230))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(700, 150, 50, 50))
        self.pushButton_3.setStyleSheet("background-color: rgba(255, 255, 255, 10);\n"
"border : none;")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.currentTrack = QtWidgets.QLabel(self.frame)
        self.currentTrack.setGeometry(QtCore.QRect(540, 100, 200, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.currentTrack.setFont(font)
        self.currentTrack.setAlignment(QtCore.Qt.AlignCenter)
        self.currentTrack.setObjectName("currentTrack")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(530, 150, 50, 50))
        self.pushButton_4.setStyleSheet("background-color: rgba(255, 255, 255, 10);\n"
"border : none;")
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 145, 60, 60))
        self.pushButton_2.setStyleSheet("background-color: rgba(255, 255, 255, 10);\n"
"border : none;")
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.currentTime = QtWidgets.QLabel(self.frame)
        self.currentTime.setGeometry(QtCore.QRect(280, 0, 240, 91))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(36)
        self.currentTime.setFont(font)
        self.currentTime.setAlignment(QtCore.Qt.AlignCenter)
        self.currentTime.setObjectName("currentTime")
        self.auswahlbox2 = QtWidgets.QComboBox(self.frame)
        self.auswahlbox2.setGeometry(QtCore.QRect(15, 110, 225, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.auswahlbox2.setFont(font)
        self.auswahlbox2.setObjectName("auswahlbox2")
        self.auswahlbox3 = QtWidgets.QComboBox(self.frame)
        self.auswahlbox3.setGeometry(QtCore.QRect(15, 155, 225, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.auswahlbox3.setFont(font)
        self.auswahlbox3.setObjectName("auswahlbox3")
        self.auswahlbox1 = QtWidgets.QComboBox(self.frame)
        self.auswahlbox1.setGeometry(QtCore.QRect(15, 65, 225, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.auswahlbox1.setFont(font)
        self.auswahlbox1.setObjectName("auswahlbox1")
        self.auswahlbox1.addItem("")
        self.auswahlbox1.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.uhrzeit1.setText(_translate("MainWindow", "uhrzeit1"))
        self.temperatur1.setText(_translate("MainWindow", "temperatur1"))
        self.wind1.setText(_translate("MainWindow", "wind1"))
        self.regen1.setText(_translate("MainWindow", "regen1"))
        self.regen2.setText(_translate("MainWindow", "regen2"))
        self.uhrzeit2.setText(_translate("MainWindow", "uhrzeit2"))
        self.temperatur2.setText(_translate("MainWindow", "temperatur2"))
        self.wind2.setText(_translate("MainWindow", "wind2"))
        self.regen3.setText(_translate("MainWindow", "regen3"))
        self.uhrzeit3.setText(_translate("MainWindow", "uhrzeit3"))
        self.temperatur3.setText(_translate("MainWindow", "temperatur3"))
        self.wind3.setText(_translate("MainWindow", "wind3"))
        self.regen4.setText(_translate("MainWindow", "regen4"))
        self.uhrzeit4.setText(_translate("MainWindow", "uhrzeit4"))
        self.temperatur4.setText(_translate("MainWindow", "temperatur4"))
        self.wind4.setText(_translate("MainWindow", "wind4"))
        self.regen5.setText(_translate("MainWindow", "regen5"))
        self.uhrzeit5.setText(_translate("MainWindow", "uhrzeit5"))
        self.temperatur5.setText(_translate("MainWindow", "temperatur5"))
        self.wind5.setText(_translate("MainWindow", "wind5"))
        self.regen6.setText(_translate("MainWindow", "regen6"))
        self.uhrzeit6.setText(_translate("MainWindow", "uhrzeit6"))
        self.temperatur6.setText(_translate("MainWindow", "temperatur6"))
        self.wind6.setText(_translate("MainWindow", "wind6"))
        self.currentTrack.setText(_translate("MainWindow", "currentTrack"))
        self.currentTime.setText(_translate("MainWindow", "currentTime"))
        self.auswahlbox1.setItemText(0, _translate("MainWindow", "Radio"))
        self.auswahlbox1.setItemText(1, _translate("MainWindow", "Audiobook"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
